import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/context/ThemeContext";
import Header from "@/components/Header";

// Import Inter properly
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});
 
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" className={`${inter.variable}  ${geistMono.variable} `}>
      <body
        className={`${inter.className} antialiased dark:bg-dark  `}
        cz-shortcut-listen="true"
      >
        <ThemeProvider>
          <Header />
          <div className="container my-2 dark:bg-dark mx-auto py-8">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
